# Generated by Django 3.2.14 on 2022-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_test_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-03-19'),
            preserve_default=False,
        ),
    ]
